PLAYERS = [
    {"id": "oliver",   "displayName": "Oliver",   "gamertag": "Hopa#Hopa",              "url": "https://www.leagueofgraphs.com/summoner/euw/Hopa-Hopa"},
    {"id": "eirik",    "displayName": "Eirik",    "gamertag": "ErikBby69#EUW",           "url": "https://www.leagueofgraphs.com/summoner/euw/ErikBby69-EUW"},
    {"id": "marcus",   "displayName": "Marcus",   "gamertag": "Easy Geometry#EUW",       "url": "https://www.leagueofgraphs.com/summoner/euw/Easy+Geometry-EUW"},
    {"id": "minh",     "displayName": "Minh",     "gamertag": "KingOfTheWolvez#EUW",     "url": "https://www.leagueofgraphs.com/summoner/euw/KingOfTheWolvez-EUW"},
    {"id": "jon",      "displayName": "Jon",      "gamertag": "Markemouse#Monke",        "url": "https://www.leagueofgraphs.com/summoner/euw/Markemouse-Monke"},
    {"id": "daniel",   "displayName": "Daniel",   "gamertag": "MczExperttt#EUW",         "url": "https://www.leagueofgraphs.com/summoner/euw/MczExperttt-EUW"},
    {"id": "nontagan", "displayName": "Nontagan", "gamertag": "MrHipsterYip#EUW",        "url": "https://www.leagueofgraphs.com/summoner/euw/MrHipsterYip-EUW"},
    {"id": "tim",      "displayName": "Tim",      "gamertag": "Pamit#EUW",               "url": "https://www.leagueofgraphs.com/summoner/euw/Pamit-EUW"},
    {"id": "sigurd",   "displayName": "Sigurd",   "gamertag": "Pog0p#EUW",               "url": "https://www.leagueofgraphs.com/summoner/euw/Pog0p-EUW"},
    {"id": "simon",    "displayName": "Simon",    "gamertag": "sXBLACKPHANTOMXs#2003",   "url": "https://www.leagueofgraphs.com/summoner/euw/sXBLACKPHANTOMXs-2003"},
    {"id": "fredrik",  "displayName": "Fredrik",  "gamertag": "XxVortexSpeedxX#3845",    "url": "https://www.leagueofgraphs.com/summoner/euw/XxVortexSpeedxX-3845"},
    {"id": "adrian",   "displayName": "Adrian",   "gamertag": "Requiem#9749",            "url": "https://www.leagueofgraphs.com/summoner/euw/Requiem-9749"},
    {"id": "sigurdn",  "displayName": "Sigurd N", "gamertag": "Mr Naess#EUW",            "url": "https://www.leagueofgraphs.com/summoner/euw/Mr+Naess-EUW"},
    {"id": "elias",    "displayName": "Elias",    "gamertag": "Hotdogmaster64#EUW",      "url": "https://www.leagueofgraphs.com/summoner/euw/Hotdogmaster64-EUW"},
]
