// Generated by scripts/sync_champion_assets.py. Do not edit by hand.
export const CHAMPION_CATALOG = [
  {
    "name": "Aatrox",
    "slug": "Aatrox",
    "imageUrl": "/champions/Aatrox.png"
  },
  {
    "name": "Ahri",
    "slug": "Ahri",
    "imageUrl": "/champions/Ahri.png"
  },
  {
    "name": "Akali",
    "slug": "Akali",
    "imageUrl": "/champions/Akali.png"
  },
  {
    "name": "Akshan",
    "slug": "Akshan",
    "imageUrl": "/champions/Akshan.png"
  },
  {
    "name": "Alistar",
    "slug": "Alistar",
    "imageUrl": "/champions/Alistar.png"
  },
  {
    "name": "Ambessa",
    "slug": "Ambessa",
    "imageUrl": "/champions/Ambessa.png"
  },
  {
    "name": "Amumu",
    "slug": "Amumu",
    "imageUrl": "/champions/Amumu.png"
  },
  {
    "name": "Anivia",
    "slug": "Anivia",
    "imageUrl": "/champions/Anivia.png"
  },
  {
    "name": "Annie",
    "slug": "Annie",
    "imageUrl": "/champions/Annie.png"
  },
  {
    "name": "Aphelios",
    "slug": "Aphelios",
    "imageUrl": "/champions/Aphelios.png"
  },
  {
    "name": "Ashe",
    "slug": "Ashe",
    "imageUrl": "/champions/Ashe.png"
  },
  {
    "name": "Aurelion Sol",
    "slug": "AurelionSol",
    "imageUrl": "/champions/AurelionSol.png"
  },
  {
    "name": "Aurora",
    "slug": "Aurora",
    "imageUrl": "/champions/Aurora.png"
  },
  {
    "name": "Azir",
    "slug": "Azir",
    "imageUrl": "/champions/Azir.png"
  },
  {
    "name": "Bard",
    "slug": "Bard",
    "imageUrl": "/champions/Bard.png"
  },
  {
    "name": "Bel'Veth",
    "slug": "Belveth",
    "imageUrl": "/champions/Belveth.png"
  },
  {
    "name": "Blitzcrank",
    "slug": "Blitzcrank",
    "imageUrl": "/champions/Blitzcrank.png"
  },
  {
    "name": "Brand",
    "slug": "Brand",
    "imageUrl": "/champions/Brand.png"
  },
  {
    "name": "Braum",
    "slug": "Braum",
    "imageUrl": "/champions/Braum.png"
  },
  {
    "name": "Briar",
    "slug": "Briar",
    "imageUrl": "/champions/Briar.png"
  },
  {
    "name": "Caitlyn",
    "slug": "Caitlyn",
    "imageUrl": "/champions/Caitlyn.png"
  },
  {
    "name": "Camille",
    "slug": "Camille",
    "imageUrl": "/champions/Camille.png"
  },
  {
    "name": "Cassiopeia",
    "slug": "Cassiopeia",
    "imageUrl": "/champions/Cassiopeia.png"
  },
  {
    "name": "Cho'Gath",
    "slug": "Chogath",
    "imageUrl": "/champions/Chogath.png"
  },
  {
    "name": "Corki",
    "slug": "Corki",
    "imageUrl": "/champions/Corki.png"
  },
  {
    "name": "Darius",
    "slug": "Darius",
    "imageUrl": "/champions/Darius.png"
  },
  {
    "name": "Diana",
    "slug": "Diana",
    "imageUrl": "/champions/Diana.png"
  },
  {
    "name": "Dr. Mundo",
    "slug": "DrMundo",
    "imageUrl": "/champions/DrMundo.png"
  },
  {
    "name": "Draven",
    "slug": "Draven",
    "imageUrl": "/champions/Draven.png"
  },
  {
    "name": "Ekko",
    "slug": "Ekko",
    "imageUrl": "/champions/Ekko.png"
  },
  {
    "name": "Elise",
    "slug": "Elise",
    "imageUrl": "/champions/Elise.png"
  },
  {
    "name": "Evelynn",
    "slug": "Evelynn",
    "imageUrl": "/champions/Evelynn.png"
  },
  {
    "name": "Ezreal",
    "slug": "Ezreal",
    "imageUrl": "/champions/Ezreal.png"
  },
  {
    "name": "Fiddlesticks",
    "slug": "Fiddlesticks",
    "imageUrl": "/champions/Fiddlesticks.png"
  },
  {
    "name": "Fiora",
    "slug": "Fiora",
    "imageUrl": "/champions/Fiora.png"
  },
  {
    "name": "Fizz",
    "slug": "Fizz",
    "imageUrl": "/champions/Fizz.png"
  },
  {
    "name": "Galio",
    "slug": "Galio",
    "imageUrl": "/champions/Galio.png"
  },
  {
    "name": "Gangplank",
    "slug": "Gangplank",
    "imageUrl": "/champions/Gangplank.png"
  },
  {
    "name": "Garen",
    "slug": "Garen",
    "imageUrl": "/champions/Garen.png"
  },
  {
    "name": "Gnar",
    "slug": "Gnar",
    "imageUrl": "/champions/Gnar.png"
  },
  {
    "name": "Gragas",
    "slug": "Gragas",
    "imageUrl": "/champions/Gragas.png"
  },
  {
    "name": "Graves",
    "slug": "Graves",
    "imageUrl": "/champions/Graves.png"
  },
  {
    "name": "Gwen",
    "slug": "Gwen",
    "imageUrl": "/champions/Gwen.png"
  },
  {
    "name": "Hecarim",
    "slug": "Hecarim",
    "imageUrl": "/champions/Hecarim.png"
  },
  {
    "name": "Heimerdinger",
    "slug": "Heimerdinger",
    "imageUrl": "/champions/Heimerdinger.png"
  },
  {
    "name": "Hwei",
    "slug": "Hwei",
    "imageUrl": "/champions/Hwei.png"
  },
  {
    "name": "Illaoi",
    "slug": "Illaoi",
    "imageUrl": "/champions/Illaoi.png"
  },
  {
    "name": "Irelia",
    "slug": "Irelia",
    "imageUrl": "/champions/Irelia.png"
  },
  {
    "name": "Ivern",
    "slug": "Ivern",
    "imageUrl": "/champions/Ivern.png"
  },
  {
    "name": "Janna",
    "slug": "Janna",
    "imageUrl": "/champions/Janna.png"
  },
  {
    "name": "Jarvan IV",
    "slug": "JarvanIV",
    "imageUrl": "/champions/JarvanIV.png"
  },
  {
    "name": "Jax",
    "slug": "Jax",
    "imageUrl": "/champions/Jax.png"
  },
  {
    "name": "Jayce",
    "slug": "Jayce",
    "imageUrl": "/champions/Jayce.png"
  },
  {
    "name": "Jhin",
    "slug": "Jhin",
    "imageUrl": "/champions/Jhin.png"
  },
  {
    "name": "Jinx",
    "slug": "Jinx",
    "imageUrl": "/champions/Jinx.png"
  },
  {
    "name": "K'Sante",
    "slug": "KSante",
    "imageUrl": "/champions/KSante.png"
  },
  {
    "name": "Kai'Sa",
    "slug": "Kaisa",
    "imageUrl": "/champions/Kaisa.png"
  },
  {
    "name": "Kalista",
    "slug": "Kalista",
    "imageUrl": "/champions/Kalista.png"
  },
  {
    "name": "Karma",
    "slug": "Karma",
    "imageUrl": "/champions/Karma.png"
  },
  {
    "name": "Karthus",
    "slug": "Karthus",
    "imageUrl": "/champions/Karthus.png"
  },
  {
    "name": "Kassadin",
    "slug": "Kassadin",
    "imageUrl": "/champions/Kassadin.png"
  },
  {
    "name": "Katarina",
    "slug": "Katarina",
    "imageUrl": "/champions/Katarina.png"
  },
  {
    "name": "Kayle",
    "slug": "Kayle",
    "imageUrl": "/champions/Kayle.png"
  },
  {
    "name": "Kayn",
    "slug": "Kayn",
    "imageUrl": "/champions/Kayn.png"
  },
  {
    "name": "Kennen",
    "slug": "Kennen",
    "imageUrl": "/champions/Kennen.png"
  },
  {
    "name": "Kha'Zix",
    "slug": "Khazix",
    "imageUrl": "/champions/Khazix.png"
  },
  {
    "name": "Kindred",
    "slug": "Kindred",
    "imageUrl": "/champions/Kindred.png"
  },
  {
    "name": "Kled",
    "slug": "Kled",
    "imageUrl": "/champions/Kled.png"
  },
  {
    "name": "Kog'Maw",
    "slug": "KogMaw",
    "imageUrl": "/champions/KogMaw.png"
  },
  {
    "name": "LeBlanc",
    "slug": "Leblanc",
    "imageUrl": "/champions/Leblanc.png"
  },
  {
    "name": "Lee Sin",
    "slug": "LeeSin",
    "imageUrl": "/champions/LeeSin.png"
  },
  {
    "name": "Leona",
    "slug": "Leona",
    "imageUrl": "/champions/Leona.png"
  },
  {
    "name": "Lillia",
    "slug": "Lillia",
    "imageUrl": "/champions/Lillia.png"
  },
  {
    "name": "Lissandra",
    "slug": "Lissandra",
    "imageUrl": "/champions/Lissandra.png"
  },
  {
    "name": "Lucian",
    "slug": "Lucian",
    "imageUrl": "/champions/Lucian.png"
  },
  {
    "name": "Lulu",
    "slug": "Lulu",
    "imageUrl": "/champions/Lulu.png"
  },
  {
    "name": "Lux",
    "slug": "Lux",
    "imageUrl": "/champions/Lux.png"
  },
  {
    "name": "Malphite",
    "slug": "Malphite",
    "imageUrl": "/champions/Malphite.png"
  },
  {
    "name": "Malzahar",
    "slug": "Malzahar",
    "imageUrl": "/champions/Malzahar.png"
  },
  {
    "name": "Maokai",
    "slug": "Maokai",
    "imageUrl": "/champions/Maokai.png"
  },
  {
    "name": "Master Yi",
    "slug": "MasterYi",
    "imageUrl": "/champions/MasterYi.png"
  },
  {
    "name": "Mel",
    "slug": "Mel",
    "imageUrl": "/champions/Mel.png"
  },
  {
    "name": "Milio",
    "slug": "Milio",
    "imageUrl": "/champions/Milio.png"
  },
  {
    "name": "Miss Fortune",
    "slug": "MissFortune",
    "imageUrl": "/champions/MissFortune.png"
  },
  {
    "name": "Mordekaiser",
    "slug": "Mordekaiser",
    "imageUrl": "/champions/Mordekaiser.png"
  },
  {
    "name": "Morgana",
    "slug": "Morgana",
    "imageUrl": "/champions/Morgana.png"
  },
  {
    "name": "Naafiri",
    "slug": "Naafiri",
    "imageUrl": "/champions/Naafiri.png"
  },
  {
    "name": "Nami",
    "slug": "Nami",
    "imageUrl": "/champions/Nami.png"
  },
  {
    "name": "Nasus",
    "slug": "Nasus",
    "imageUrl": "/champions/Nasus.png"
  },
  {
    "name": "Nautilus",
    "slug": "Nautilus",
    "imageUrl": "/champions/Nautilus.png"
  },
  {
    "name": "Neeko",
    "slug": "Neeko",
    "imageUrl": "/champions/Neeko.png"
  },
  {
    "name": "Nidalee",
    "slug": "Nidalee",
    "imageUrl": "/champions/Nidalee.png"
  },
  {
    "name": "Nilah",
    "slug": "Nilah",
    "imageUrl": "/champions/Nilah.png"
  },
  {
    "name": "Nocturne",
    "slug": "Nocturne",
    "imageUrl": "/champions/Nocturne.png"
  },
  {
    "name": "Nunu & Willump",
    "slug": "Nunu",
    "imageUrl": "/champions/Nunu.png"
  },
  {
    "name": "Olaf",
    "slug": "Olaf",
    "imageUrl": "/champions/Olaf.png"
  },
  {
    "name": "Orianna",
    "slug": "Orianna",
    "imageUrl": "/champions/Orianna.png"
  },
  {
    "name": "Ornn",
    "slug": "Ornn",
    "imageUrl": "/champions/Ornn.png"
  },
  {
    "name": "Pantheon",
    "slug": "Pantheon",
    "imageUrl": "/champions/Pantheon.png"
  },
  {
    "name": "Poppy",
    "slug": "Poppy",
    "imageUrl": "/champions/Poppy.png"
  },
  {
    "name": "Pyke",
    "slug": "Pyke",
    "imageUrl": "/champions/Pyke.png"
  },
  {
    "name": "Qiyana",
    "slug": "Qiyana",
    "imageUrl": "/champions/Qiyana.png"
  },
  {
    "name": "Quinn",
    "slug": "Quinn",
    "imageUrl": "/champions/Quinn.png"
  },
  {
    "name": "Rakan",
    "slug": "Rakan",
    "imageUrl": "/champions/Rakan.png"
  },
  {
    "name": "Rammus",
    "slug": "Rammus",
    "imageUrl": "/champions/Rammus.png"
  },
  {
    "name": "Rek'Sai",
    "slug": "RekSai",
    "imageUrl": "/champions/RekSai.png"
  },
  {
    "name": "Rell",
    "slug": "Rell",
    "imageUrl": "/champions/Rell.png"
  },
  {
    "name": "Renata Glasc",
    "slug": "Renata",
    "imageUrl": "/champions/Renata.png"
  },
  {
    "name": "Renekton",
    "slug": "Renekton",
    "imageUrl": "/champions/Renekton.png"
  },
  {
    "name": "Rengar",
    "slug": "Rengar",
    "imageUrl": "/champions/Rengar.png"
  },
  {
    "name": "Riven",
    "slug": "Riven",
    "imageUrl": "/champions/Riven.png"
  },
  {
    "name": "Rumble",
    "slug": "Rumble",
    "imageUrl": "/champions/Rumble.png"
  },
  {
    "name": "Ryze",
    "slug": "Ryze",
    "imageUrl": "/champions/Ryze.png"
  },
  {
    "name": "Samira",
    "slug": "Samira",
    "imageUrl": "/champions/Samira.png"
  },
  {
    "name": "Sejuani",
    "slug": "Sejuani",
    "imageUrl": "/champions/Sejuani.png"
  },
  {
    "name": "Senna",
    "slug": "Senna",
    "imageUrl": "/champions/Senna.png"
  },
  {
    "name": "Seraphine",
    "slug": "Seraphine",
    "imageUrl": "/champions/Seraphine.png"
  },
  {
    "name": "Sett",
    "slug": "Sett",
    "imageUrl": "/champions/Sett.png"
  },
  {
    "name": "Shaco",
    "slug": "Shaco",
    "imageUrl": "/champions/Shaco.png"
  },
  {
    "name": "Shen",
    "slug": "Shen",
    "imageUrl": "/champions/Shen.png"
  },
  {
    "name": "Shyvana",
    "slug": "Shyvana",
    "imageUrl": "/champions/Shyvana.png"
  },
  {
    "name": "Singed",
    "slug": "Singed",
    "imageUrl": "/champions/Singed.png"
  },
  {
    "name": "Sion",
    "slug": "Sion",
    "imageUrl": "/champions/Sion.png"
  },
  {
    "name": "Sivir",
    "slug": "Sivir",
    "imageUrl": "/champions/Sivir.png"
  },
  {
    "name": "Skarner",
    "slug": "Skarner",
    "imageUrl": "/champions/Skarner.png"
  },
  {
    "name": "Smolder",
    "slug": "Smolder",
    "imageUrl": "/champions/Smolder.png"
  },
  {
    "name": "Sona",
    "slug": "Sona",
    "imageUrl": "/champions/Sona.png"
  },
  {
    "name": "Soraka",
    "slug": "Soraka",
    "imageUrl": "/champions/Soraka.png"
  },
  {
    "name": "Swain",
    "slug": "Swain",
    "imageUrl": "/champions/Swain.png"
  },
  {
    "name": "Sylas",
    "slug": "Sylas",
    "imageUrl": "/champions/Sylas.png"
  },
  {
    "name": "Syndra",
    "slug": "Syndra",
    "imageUrl": "/champions/Syndra.png"
  },
  {
    "name": "Tahm Kench",
    "slug": "TahmKench",
    "imageUrl": "/champions/TahmKench.png"
  },
  {
    "name": "Taliyah",
    "slug": "Taliyah",
    "imageUrl": "/champions/Taliyah.png"
  },
  {
    "name": "Talon",
    "slug": "Talon",
    "imageUrl": "/champions/Talon.png"
  },
  {
    "name": "Taric",
    "slug": "Taric",
    "imageUrl": "/champions/Taric.png"
  },
  {
    "name": "Teemo",
    "slug": "Teemo",
    "imageUrl": "/champions/Teemo.png"
  },
  {
    "name": "Thresh",
    "slug": "Thresh",
    "imageUrl": "/champions/Thresh.png"
  },
  {
    "name": "Tristana",
    "slug": "Tristana",
    "imageUrl": "/champions/Tristana.png"
  },
  {
    "name": "Trundle",
    "slug": "Trundle",
    "imageUrl": "/champions/Trundle.png"
  },
  {
    "name": "Tryndamere",
    "slug": "Tryndamere",
    "imageUrl": "/champions/Tryndamere.png"
  },
  {
    "name": "Twisted Fate",
    "slug": "TwistedFate",
    "imageUrl": "/champions/TwistedFate.png"
  },
  {
    "name": "Twitch",
    "slug": "Twitch",
    "imageUrl": "/champions/Twitch.png"
  },
  {
    "name": "Udyr",
    "slug": "Udyr",
    "imageUrl": "/champions/Udyr.png"
  },
  {
    "name": "Urgot",
    "slug": "Urgot",
    "imageUrl": "/champions/Urgot.png"
  },
  {
    "name": "Varus",
    "slug": "Varus",
    "imageUrl": "/champions/Varus.png"
  },
  {
    "name": "Vayne",
    "slug": "Vayne",
    "imageUrl": "/champions/Vayne.png"
  },
  {
    "name": "Veigar",
    "slug": "Veigar",
    "imageUrl": "/champions/Veigar.png"
  },
  {
    "name": "Vel'Koz",
    "slug": "Velkoz",
    "imageUrl": "/champions/Velkoz.png"
  },
  {
    "name": "Vex",
    "slug": "Vex",
    "imageUrl": "/champions/Vex.png"
  },
  {
    "name": "Vi",
    "slug": "Vi",
    "imageUrl": "/champions/Vi.png"
  },
  {
    "name": "Viego",
    "slug": "Viego",
    "imageUrl": "/champions/Viego.png"
  },
  {
    "name": "Viktor",
    "slug": "Viktor",
    "imageUrl": "/champions/Viktor.png"
  },
  {
    "name": "Vladimir",
    "slug": "Vladimir",
    "imageUrl": "/champions/Vladimir.png"
  },
  {
    "name": "Volibear",
    "slug": "Volibear",
    "imageUrl": "/champions/Volibear.png"
  },
  {
    "name": "Warwick",
    "slug": "Warwick",
    "imageUrl": "/champions/Warwick.png"
  },
  {
    "name": "Wukong",
    "slug": "MonkeyKing",
    "imageUrl": "/champions/MonkeyKing.png"
  },
  {
    "name": "Xayah",
    "slug": "Xayah",
    "imageUrl": "/champions/Xayah.png"
  },
  {
    "name": "Xerath",
    "slug": "Xerath",
    "imageUrl": "/champions/Xerath.png"
  },
  {
    "name": "Xin Zhao",
    "slug": "XinZhao",
    "imageUrl": "/champions/XinZhao.png"
  },
  {
    "name": "Yasuo",
    "slug": "Yasuo",
    "imageUrl": "/champions/Yasuo.png"
  },
  {
    "name": "Yone",
    "slug": "Yone",
    "imageUrl": "/champions/Yone.png"
  },
  {
    "name": "Yorick",
    "slug": "Yorick",
    "imageUrl": "/champions/Yorick.png"
  },
  {
    "name": "Yunara",
    "slug": "Yunara",
    "imageUrl": "/champions/Yunara.png"
  },
  {
    "name": "Yuumi",
    "slug": "Yuumi",
    "imageUrl": "/champions/Yuumi.png"
  },
  {
    "name": "Zaahen",
    "slug": "Zaahen",
    "imageUrl": "/champions/Zaahen.png"
  },
  {
    "name": "Zac",
    "slug": "Zac",
    "imageUrl": "/champions/Zac.png"
  },
  {
    "name": "Zed",
    "slug": "Zed",
    "imageUrl": "/champions/Zed.png"
  },
  {
    "name": "Zeri",
    "slug": "Zeri",
    "imageUrl": "/champions/Zeri.png"
  },
  {
    "name": "Ziggs",
    "slug": "Ziggs",
    "imageUrl": "/champions/Ziggs.png"
  },
  {
    "name": "Zilean",
    "slug": "Zilean",
    "imageUrl": "/champions/Zilean.png"
  },
  {
    "name": "Zoe",
    "slug": "Zoe",
    "imageUrl": "/champions/Zoe.png"
  },
  {
    "name": "Zyra",
    "slug": "Zyra",
    "imageUrl": "/champions/Zyra.png"
  }
];
